### ISSUE TITLE
Eddy on Pop!OS v22.04 fails to install or uninstall downloaded DEB files

### ISSUE THREAD

**Issue by wagnerck** [system76/eddy#9]
Using Eddy to install downloaded DEB files does not work. Double-clicking on the DEB file in the Files app or loading it manually after starting Eddy first has the same effect.

For example: download https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb to the Downloads folder, and then double-click on it in the Files app. Eddy will open, and show the Install button. Clicking Install will show a "Finished" text very briefly, but immediately go back to the same window with a green Install button.

![image](https://user-images.githubusercontent.com/96320715/161313676-14eefd32-f94f-4bf6-81c0-162661111046.png)

Installing the app manually with `sudo apt install ./1password-latest.deb` works fine. After doing so, opening up the same DEB file in Eddy now shows the red Uninstall button, which does exactly the same thing as the Install button did (say "Finished" briefly and then go back to the same button).

I've replicated this problem on both a standalone laptop (non-System76) and with a Pop!OS install in a virtual machine.

**Comment by mmstick** [comment]
As far as I can tell, it's a PolicyKit error because it never gives the PolicyKit dialog requesting for permission to install the package.

**Comment by wagnerck** [comment]
Running `sudo com.github.donadigo.eddy` works correctly, so I think you're right.

[edit] Wait, tested that in the wrong VM.

[edit two] Running `sudo com.github.donadigo.eddy` works in the v22.04 VM, confirmed.

**Comment by mmstick** [comment]
I see that there's an issue upstream for this error. It would seem that there's a bug in packagekit's `Task.install_files_` methods which is not giving that dialog. Seems like it'd be worth it to switch to using `pkexec apt install` instead.

**Comment by wagnerck** [comment]
If that'll provide the same prompt and functionality then by all means, simpler is better.

**Comment by wagnerck** [comment]
Can confirm that this works with the test file from before, although it no longer has the progress bar. Thanks for the quick fix.
